title: ynishimura blog
description: My Personal Blog
author: ynishimura
logo: /static/img/avatar.png
github: https://github.com/
about: Infrastructure Engineer
disqus_shortname: aboutashu
# google_analytics: UA-72862926-1
urls:
    - text: Home
      url: /
      icon: fa-home
      layout: post
    - text: About
      url: /about/
      icon: fa-comments
    - text: Projects
      url: /projects/
      icon: fa-desktop
    - text: Chart
      url: '#'
      icon: fa-bar-chart
    - text: Diary
      url: '#'
      icon: fa-asterisk
    - text: XML Feed
      url: /feed.xml
      icon: fa-feed

social:
    - icon: fa-facebook
      link: '#'
    - icon: fa-github
      link: '#'
    - icon: fa-twitter
      link: '#'
    - icon: fa-linkedin
      link: '#'
    - icon: fa-stack-exchange
      link: '#'

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
