title: ynishimura blog
description: My Personal Blog
author: ynishimura
logo: /static/img/avatar.gif
github: https://github.com/
about: Infra Engineer Blog
disqus_shortname: aboutashu
encoding: utf-8
google_analytics: UA-84353632-1
urls:
    - text: Home
      url: /
      icon: fa-home
      layout: post
    - text: About
      url: /about/
      icon: fa-comments
    - text: Projects
      url: /projects/
      icon: fa-desktop
    - text: Category
      url: /category/
      icon: fa-search
    - text: Diary
      url: '#'
      icon: fa-asterisk
    - text: XML Feed
      url: /feed.xml
      icon: fa-feed

social:
#    - icon: fa-facebook
#      link: '#'
    - icon: fa-github
      link: 'https://github.com/'
    - icon: fa-twitter
      link: '#'
    - icon: fa-stack-overflow
      link: 'http://ja.stackoverflow.com/'
#    - icon: fa-stack-exchange
#     link: '#'

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
